config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'assignments#index'
  resources :assignments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/print_number_words.rb
class PrintNumberWords

  def self.get_strings_from_number(number)
    digit_letters =  {"2" => ['A','B','C'],"3" => ['D','E','F'],"4" => ['G','H','I'],"5" => ['J','K','L'],
  	  	 						"6" => ['M','N','O'],"7" => ['P','Q','R','S'],"8" => ['T','U','V'],"9" => ['W','X','Y','Z']}

    dictionary = []
    file_path = Rails.root.join("db","dictionary.txt")
    File.foreach( file_path ) do |word|
      dictionary.push word.chop.to_s
    end
    get_strings = []
    words = number.chars.map{|digit|digit_letters[digit]}

    matches = {}
    total = words.length - 1
    
    for i in (2..total)
      array1 = words[0..i]
      array2 = words[i + 1..total]
      if !(array1.length < 3 || array2.length < 3)
      	combination_first = array1.shift.product(*array1).map(&:join)
      	combination_last = array2.shift.product(*array2).map(&:join) 
      	matches[i] =  [(combination_first & dictionary), (combination_last & dictionary)] 
      end
    end  

    matches.each do |key, array|
     unless (array.first.blank? || array.last.blank?)
	      array.first.product(array.last).each do |words|
	        get_strings << words
	      end
    	end
    end


     get_strings << (words.shift.product(*words).map(&:join) & dictionary).join(", ")

    
    get_strings
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

	def index
		@error_message, @word_combinations = nil,nil
	  if params[:number].present? && params[:number].length != 10
	  	  @error_message =  "Enter 10 digit number between 2 to 9 "
	  	return @error_message   
	  elsif params[:number].present? && params[:number].split("").select{|a| a.to_i == 0 || a.to_i ==1}.length >0
	  	 @error_message =  "Number should be between 2 to 9"
	  	return @error_message 
    else
	 		@word_combinations = PrintNumberWords.get_strings_from_number(params[:number]) if params[:number]	
    end
   return @word_combinations
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/index.html.erb
<%= form_tag(assignments_path, method: "get") do %>
  <%= @error_message  %>
 
  <p>
    <%= "Enter Number" %><br>
    <%= number_field_tag 'number', nil%>
  </p>
 
  <p>
    <%= submit_tag("Submit", :name=>"submit") %>
  </p>
<% end %>

<div>
<% if @word_combinations.present? %>
 <%= @word_combinations%>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>